#!/bin/bash
STR="1.c"
echo -e "int _putchar(char c){}" >> $STR;
STR="2.c"
echo -e "int _islower(int c){}" >> $STR;
STR="3.c"
echo -e "int _isalpha(int c){}" >> $STR;
STR="4.c"
echo -e "int _abs(int n){}" >> $STR;
STR="5.c"
echo -e "int _isupper(int c){}" >> $STR;
STR="6.c"
echo -e "int _isdigit(int c){}" >> $STR;
STR="7.c"
echo -e "int _strlen(char *s){}" >> $STR;
STR="8.c"
echo -e "void _puts(char *s){}" >> $STR;
STR="9.c"
echo -e "char *_strcpy(char *dest, char *src){}" >> $STR;
STR="10.c"
echo -e "int _atoi(char *s){}" >> $STR;
STR="11.c"
echo -e "char *_strcat(char *dest, char *src){}" >> $STR;
STR="12.c"
echo -e "char *_strncat(char *dest, char *src, int n){}" >> $STR;
STR="13.c"
echo -e "char *_strncpy(char *dest, char *src, int n){}" >> $STR;
STR="14.c"
echo -e "int _strcmp(char *s1, char *s2){}" >> $STR;
STR="15.c"
echo -e "char *_memset(char *s, char b, unsigned int n){}" >> $STR;
STR="16.c"
echo -e "char *_memcpy(char *dest, char *src, unsigned int n){}" >> $STR;
STR="17.c"
echo -e "char *_strchr(char *s, char c){}" >> $STR;
STR="18.c"
echo -e "unsigned int _strspn(char *s, char *accept){}" >> $STR;
STR="19.c"
echo -e "char *_strpbrk(char *s, char *accept){}" >> $STR;
STR="20.c"
echo -e "char *_strstr(char *haystack, char *needle){}" >> $STR;
